#!/data/data/com.termux/files/usr/bin/bash
clear

echo '-------------------------'
echo 'You started base-installer'
echo 'Author: Matvey3850'
echo 'GitHub: github.com/Matvey3850/utms'
echo '-------------------------'
echo '     '

echo '-------------------------'
echo 'SETTING PROPERTIES'
echo '-------------------------'
cd ~
mkdir apps
cd ~/apps
mkdir _advanced
mkdir smsbomber
cd ~

echo '-------------------------'
echo 'UPDATING PACKAGES'
echo '-------------------------'
pkg update -y
pkg upgrade -y

echo '-------------------------'
echo 'INSTALLING REPOSITORIES'
echo '-------------------------'
pkg install root-repo -y
pkg install unstable-repo -y

echo '-------------------------'
echo 'INSTALLING PACKAGES'
echo '-------------------------'
pkg install bash-completion -y
pkg install tsu -y
pkg install man -y
pkg install vim -y
pkg install wget -y
pkg install python -y
pkg install php -y
pkg install wireless-tools -y
pkg install net-tools -y
pkg install openssh -y